// <auto-generated />
using System;
using AspWebProgramming.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspWebProgram.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231227235651_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspWebProgramming.Data.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"), 1L, 1);

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Adminler");
                });

            modelBuilder.Entity("AspWebProgramming.Data.AnaBilim", b =>
                {
                    b.Property<int?>("AnaBilimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("AnaBilimId"), 1L, 1);

                    b.Property<string>("AnaBilimAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnaBilimId");

                    b.ToTable("AnaBilimler");
                });

            modelBuilder.Entity("AspWebProgramming.Data.Doktor", b =>
                {
                    b.Property<int>("DoktorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoktorId"), 1L, 1);

                    b.Property<string>("DoktorAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorAnaBilim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorBrans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorCinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorPoliklinik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorSifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoktorTc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoktorId");

                    b.ToTable("Doktorlar");
                });

            modelBuilder.Entity("AspWebProgramming.Data.Hasta", b =>
                {
                    b.Property<int>("HastaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HastaId"), 1L, 1);

                    b.Property<string>("HastaAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaCinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaEposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaSifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaTc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HastaId");

                    b.ToTable("Hastalar");
                });

            modelBuilder.Entity("AspWebProgramming.Data.Poliklinik", b =>
                {
                    b.Property<int?>("PoliklinikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("PoliklinikId"), 1L, 1);

                    b.Property<string>("PoliklinikAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoliklinikId");

                    b.ToTable("Poliklinikler");
                });

            modelBuilder.Entity("AspWebProgramming.Data.Randevu", b =>
                {
                    b.Property<int>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuId"), 1L, 1);

                    b.Property<int>("DoktorId")
                        .HasColumnType("int");

                    b.Property<int>("HastaId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("RandevuSaati")
                        .HasColumnType("time");

                    b.Property<DateTime>("RandevuTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("RandevuId");

                    b.HasIndex("DoktorId");

                    b.HasIndex("HastaId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("AspWebProgramming.Data.Randevu", b =>
                {
                    b.HasOne("AspWebProgramming.Data.Doktor", "Doktor")
                        .WithMany()
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspWebProgramming.Data.Hasta", "Hasta")
                        .WithMany()
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doktor");

                    b.Navigation("Hasta");
                });
#pragma warning restore 612, 618
        }
    }
}
